Repository viperleed/viperleed, pull requests merged in 2025-04, with the labels that each got.

#319 Automatically remove work directory upon successful execution
  doc/content/calc/example_systems/Ag(100).rst
  doc/content/calc/how_to_run.rst
  doc/content/command_line_tools.rst
  src/viperleed/calc/cli.py
  tests/calc/bookkeeper/bookkeeper/test_run_with_calc.py
  tests/calc/test_cli.py
Labels: calc, nice-to-have

#326 Search-report.csv
  doc/content/calc/files/output/searchprogresspdf.rst
  doc/content/calc/files/output/searchreportpdf.rst
  src/viperleed/calc/files/searchpdf.py
  src/viperleed/calc/sections/cleanup.py
  src/viperleed/calc/sections/search.py
Labels: enhancement, calc

#327 Bugfix doc
  doc/conf.py
  doc/content/appendix.rst
Labels: bug, documentation

#230 Building docs on Readthedocs.org
  .readthedocs.yaml
  README.md
  doc/_static/css/theme_overrides.css
  doc/index.rst
  doc/references.bib
Labels: documentation

#328 feat,doc: backport readthedocs config
  .readthedocs.yaml
  doc/_static/css/theme_overrides.css
  doc/index.rst
Labels: documentation

#329 feat,doc: backport readthedocs config
  .readthedocs.yaml
  doc/_static/css/theme_overrides.css
  doc/index.rst
Labels: documentation

#332 Fix TypeError, more SITE_DEF tests
  src/viperleed/calc/sections/superpos.py
  tests/_test_data/POSCARs/POSCAR_Pt25Rh75(100)-p(3x1)-O
  tests/_test_data/parameters/PARAMETERS_Pt25Rh75(100)-p(3x1)-O
  tests/calc/files/parameters/case_parameters.py
  tests/calc/poscar_slabs.py
Labels: calc
